module.exports = [
    require('./config/01.js'),
    require('./config/02.js'),
    require('./config/03.js'),
    require('./config/04.js'),
    require('./config/05.js'),
    require('./config/06.js'),
    require('./config/07.js'),
    require('./config/08.js'),
    require('./config/09.js'),

    require('./config/10.js'),
    require('./config/11.js'),
    require('./config/12.js'),
    require('./config/13.js'),
    require('./config/14.js'),
    require('./config/15.js'),
    require('./config/16.js'),
    require('./config/17.js'),
    require('./config/18.js'),
    require('./config/19.js'),
    require('./config/20.js'),

    require('./config/21.js'),
    require('./config/22.js'),
    require('./config/23.js'),
    require('./config/24.js'),
    require('./config/25.js'),
    require('./config/26.js'),
    require('./config/27.js'),
    require('./config/28.js'),
    require('./config/29.js'),

    require('./config/30.js'),
    require('./config/31.js'),
    require('./config/32.js'),
    require('./config/33.js'),
    require('./config/34.js'),
    require('./config/35.js'),
    require('./config/36.js'),
    require('./config/37.js'),
    require('./config/38.js'),
    require('./config/39.js'),

    require('./config/40.js'),
    require('./config/41.js'),
    require('./config/42.js')

];